# Generated by Django 4.0.4 on 2022-05-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('profile_photo', models.ImageField(upload_to='')),
                ('shortBio', models.TextField(max_length=200)),
                ('tags', models.TextField(blank=True, max_length=100)),
                ('schoolName', models.CharField(max_length=100)),
                ('schoolBoard', models.CharField(max_length=100)),
                ('Graduation', models.CharField(max_length=100)),
                ('GraduationUniversity', models.CharField(max_length=100)),
                ('postUniversity', models.CharField(max_length=100)),
                ('Linkedin', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('Github', models.CharField(max_length=100)),
                ('Instagram', models.CharField(max_length=100)),
                ('Position', models.CharField(max_length=100)),
                ('org', models.CharField(max_length=100)),
                ('From', models.DateField()),
                ('to', models.DateField()),
            ],
        ),
    ]
