# Generated by Django 4.0.4 on 2022-05-07 08:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registrationForm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='postGradUniversity',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
