# Generated by Django 4.0.4 on 2022-05-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=200)),
                ('password2', models.CharField(max_length=200)),
                ('Birthday_date', models.DateField()),
                ('username', models.CharField(blank=True, max_length=100, unique=True)),
            ],
        ),
    ]
